### ISSUE TITLE
Keeping lib-oboe in synch

### ISSUE THREAD

**Issue by carlrobert-sonymobile** [googlesamples/android-audio-high-performance#112]
Hi,
I ran into a spontaneous "Stream not closed" problem on Android 8.0 and realized it had been fixed in the upstream oboe library via https://github.com/google/oboe/commit/64f63e225101820d6d60bef073611f7838241f99

What is the recommended way of updating the oboe git, other than via a manual git operation in lib-oboe?

**Comment by ggfan** [comment]
yeah, sorry for the delay. you are right: there is not way inside the IDE to do it rather than mess it up with git on command line -- the relative the scripts is [here](https://github.com/googlesamples/android-audio-high-performance/blob/master/oboe/hello-oboe/CMakeLists.txt#L24): it is a clone.

or you could deleted "oboe/lib-oboe", and rebuilt ( will trigger another clone ), the latest code will be pulled down.

probably should add scripts: if oboe directory already exists, do an update ( prune, and fetch ). will sync with Don

**Comment by dturner** [comment]
Since oboe is a source only library (at present) probably best if we just add instructions on how to update from the command line i.e. `git pull`. BTW I am intending to move the oboe sample inside the oboe repo for exactly this reason.

**Comment by ggfan** [comment]
some info is added to readme file.
